### ISSUE TITLE
Different logo size.

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Diane--Internal---April-20-#1]
The logo is coming small in preview.
Preview link: https://s7tr3ecbpj31zclr-14531919972.shopifypreview.com/
Live link: https://ajoyforever.com/
Preview SS: 
![image](https://user-images.githubusercontent.com/97726944/163775288-f9d7e2fd-fab4-4969-8683-9c4c4196d135.png)
Live SS: 
![image](https://user-images.githubusercontent.com/97726944/163775332-b0188aff-925d-490a-8663-3e555dd14dda.png)

**Comment by devabulabbas** [comment]
@Shoaibans Resolved
